// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxzjdstvcrqmaxuexkcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4empkc3R2Y3JxbWF4dWV4a2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjYyMzMsImV4cCI6MjA2ODUwMjIzM30.gBhOxotRngE8pE5WwU8_ya0hqPoFjTYnRpvaFxfNOhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});